name: Install CFS
description: 'Configures NASA CFS bundle into the workflow filesystem'

inputs:
  upstream-ref:
    description: 'Upstream cFS ref to check out'
    default: main
  upstream-repo:
    description: 'Upstream cFS repository to use'
    default: nasa/cfs
  bundle-dir:
    description: 'Directory to stage output'
    default: cfs-bundle

runs:
  using: 'composite'
  steps:
    - name: Checkout cFS Bundle
      uses: actions/checkout@v3
      with:
        submodules: true
        repository: ${{ inputs.upstream-repo }}
        ref: ${{ inputs.upstream-ref }}
        path: ${{ inputs.bundle-dir }}

    - name: Merge PSP IODriver Patch
      shell: bash
      working-directory: ${{ inputs.bundle-dir }}/psp
      run: |
        git fetch https://github.com/jphickey/PSP.git techdev-iodriver:techdev-iodriver
        git merge --no-edit techdev-iodriver
